source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '6.0'
inhibit_all_warnings!

xcodeproj 'LGSideMenuControllerDemo'

target 'LGSideMenuControllerDemo' do
    pod 'LGSideMenuController', :path => '../'
end
